### ISSUE TITLE
[Sonic Forces] Boost from Rings no working on 7.5

### ISSUE THREAD

**Issue by Rrose80149** [thesupersonic16/HedgeModManager#1082]
[HMM_Snapshot_00072025165203.txt](https://github.com/user-attachments/files/21437404/HMM_Snapshot_00072025165203.txt)

HMM Info:
```
    Version: 7.5-0
    Args: 
    StartDir: E:\Sonic Forces\build\main\projects\exec\
    Process Level: User
    Game: Sonic Forces
    SteamGame: Sonic Forces
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(2,6): error CS1024: Preprocessor directive expected
(3,6): error CS1024: Preprocessor directive expected
(5,6): error CS1024: Preprocessor directive expected
(6,6): error CS1024: Preprocessor directive expected
(11,36): error CS0103: The name 'GameManager' does not exist in the current context
(11,59): error CS0246: The type or namespace name 'PlayerBlackboardService' could not be found (are you missing a using directive or an assembly reference?)
(16,75): error CS0246: The type or namespace name 'BlackboardBoost' could not be found (are you missing a using directive or an assembly reference?)
(21,74): error CS0246: The type or namespace name 'BlackboardItem' could not be found (are you missing a using directive or an assembly reference?)
(30,41): error CS0103: The name 'MathHelpers' does not exist in the current context

    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes(System.Collections.Generic.IEnumerable`1[HedgeModManager.Code], System.IO.Stream, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, Stream resultStream, String[] loadPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 91
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 84
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__22.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 411
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__32.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 714
    InnerException: 
```

**Comment by thesupersonic16** [comment]
It compiles just fine on HMM 7.14-3 and the latest HMM 8 version. Please update away from the 4 year old version of HMM. Closing.
